import { Notification } from "@/types";

export const sampleNotifications: Notification[] = [
  {
    id: 1,
    type: "budget",
    priority: "high",
    title: "예산 90% 도달",
    message: "Google Ads '여름 세일 캠페인'이 일일 예산의 90%를 소진했습니다.",
    timestamp: "10분 전",
    isRead: false,
    platform: "Google Ads",
    campaignName: "여름 세일 캠페인",
  },
  {
    id: 2,
    type: "performance",
    priority: "high",
    title: "전환수 급증",
    message: "Meta Ads '리타겟팅 캠페인' 전환수가 평균 대비 150% 증가했습니다.",
    timestamp: "1시간 전",
    isRead: false,
    platform: "Meta Ads",
    campaignName: "리타겟팅 캠페인",
  },
  {
    id: 3,
    type: "campaign",
    priority: "medium",
    title: "캠페인 승인 완료",
    message: "TikTok Ads '신제품 런칭' 캠페인이 승인되어 게재가 시작되었습니다.",
    timestamp: "2시간 전",
    isRead: true,
    platform: "TikTok Ads",
    campaignName: "신제품 런칭",
  },
  {
    id: 4,
    type: "performance",
    priority: "high",
    title: "CPA 상승 감지",
    message: "Amazon Ads 'Sponsored Products' 캠페인의 CPA가 목표 대비 120% 상승했습니다.",
    timestamp: "3시간 전",
    isRead: true,
    platform: "Amazon Ads",
    campaignName: "Sponsored Products",
  },
  {
    id: 5,
    type: "budget",
    priority: "medium",
    title: "월 예산 70% 소진",
    message: "이번 달 전체 광고비가 설정된 예산의 70%에 도달했습니다.",
    timestamp: "5시간 전",
    isRead: true,
  },
  {
    id: 6,
    type: "system",
    priority: "low",
    title: "주간 성과 리포트 준비 완료",
    message: "10월 2주차 성과 리포트를 확인하세요.",
    timestamp: "1일 전",
    isRead: true,
  },
];
